package com.evlarus.spendinglimit.rate.infrastructure.twelvedata;

import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.service.annotation.GetExchange;
import org.springframework.web.service.annotation.HttpExchange;

/**
 * Twelve Data REST API (https://twelvedata.com/docs#time-series). The proxy is generated by Spring;
 * base URL, timeouts and the {@code Authorization: apikey ...} header come from
 * {@code spring.http.serviceclient.twelvedata.*}, so the key never appears in URLs or access logs.
 */
@HttpExchange(accept = "application/json")
interface TwelveDataApi {

    /**
     * Candles of {@code symbol}, newest first. Dates are passed as ISO strings on purpose: formatting of
     * {@code LocalDate} parameters would depend on the conversion service and locale.
     */
    @GetExchange("/time_series")
    TimeSeriesResponse timeSeries(
            @RequestParam("symbol") String symbol,
            @RequestParam("interval") String interval,
            @RequestParam("start_date") String startDate,
            @RequestParam("end_date") String endDate);
}
